#!/bin/bash

function __rec()
{
	if [ -d $1 ];
	then
		for fn in `ls $1`
		do
			__rec $1/$fn;
		done
	else
		if [ `basename $0` != `basename $1` ]
		then
			#echo $1
			sed 's///' $1 > $1.tmp
			rm $1
			mv $1.tmp $1
		fi
	fi
}

__rec $1
